lib/phx_blog_web/router.ex
defmodule PhxBlogWeb.Router do
  use PhxBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhxBlogWeb do
  #   pipe_through :api
  # end
end

web/router.ex
defmodule PhxBlog.Router do
  use PhxBlog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlog do
    pipe_through :browser # Use the default browser stack

    get     "/",                    PostsController, :index

    get     "/users",          UserController, :index
    post    "/users",                   SocialController, :create

    get     "/users/new",      UserController, :new
    post    "/users/new",      UserController, :create

    get     "/users/me",       UserController, :edit
    put     "/users/me",       UserController, :update
    post    "/users/me",       UserController, :upload_photo
    delete  "/users/me",       UserController, :delete
    get     "/users/me/post",       PostsController, :mypost

    get     "/users/:name",    UserController, :show
    get     "/users/:name/post",    PostsController, :userpost
    post    "/users/:name/social",      SocialController, :create
    delete  "/users/:name/social",      SocialController, :delete

    get     "/post",                PostsController, :new
    post    "/post",                PostsController, :create
    get     "/post/:id/edit",       PostsController, :edit
    get     "/post/:id",            PostsController, :show
    patch   "/post/:id",            PostsController, :update
    put     "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete

    post    "/post/:id/comment",            CommentController, :create
    delete  "/post/:id/comment",            CommentController, :delete

    get     "/post/search/:query",  PostsController, :search

    get     "/login",  SessionController, :new
    post    "/login",  SessionController, :create
    delete  "/logout", SessionController, :delete
  end

#  Other scopes may use custom stacks.
  scope "/api/v1", PhxBlog do
    pipe_through :api

    get     "/users/new",      UserController, :new
    post    "/login",  SessionController, :create
    get     "/post",                PostsController, :index
    get     "/users/:id/post",      PostsController, :userpost
    post    "/post",                PostsController, :create
    patch   "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete
    get     "/post/:id",            PostsController, :show
    post    "/post/:id/comment",    CommentController, :create
    get     "/post/search/:query",  PostsController, :search

    resources "/auth", AuthController, except: [:new, :edit]

   end
end

web/models/user.ex
defmodule PhxBlog.User do
  use PhxBlog.Web, :model

  alias PhxBlog.Repo

  schema "users" do
    field :username, :string
    field :password, :string, virtual: true
    field :crypted_password, :string
    field :nickname, :string
    field :userimageurl, :string

    timestamps()
  end

  def create(changeset) do
    changeset
    |> put_change(:crypted_password, changeset.params["password"])
    |> Repo.insert()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:username, :password, :nickname, :userimageurl])
    |> unique_constraint(:username)
    |> validate_required([:username, :password])
  end

  defp hashed_password(password) do
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

web/controllers/user_controller.ex
defmodule PhxBlog.UserController do
  use PhxBlog.Web, :controller

  alias PhxBlog.User
  alias PhxBlog.Posts
  alias ExAws.S3

  @default_region "us-east-1"
  @default_bucket "my_phoenix_"

  def index(conn, _params) do
    if logged_in?(conn) do
      users = User
              |> where([u], u.username != ^current_user(conn).username)
              |> Repo.all()
    else
      users = Repo.all(User)
    end
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    unless logged_in?(conn) do
      changeset = User.changeset(%User{})
      render(conn, "new.html", changeset: changeset)
    else
      conn
      |> put_flash(:info, "既にログインしています")
      |> redirect(to: user_path(conn, :edit))
    end
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case User.create(changeset) do
      {:ok, user} ->
        S3.put_bucket(@default_bucket <> user.username, @default_region)
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:info, "User created successfully.")
        |> render("edit.html", user: user, changeset: changeset)
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"name" => username}) do
    unless username == current_user(conn).username do
      user = Repo.get_by(User, username: username)
      render(conn, "show.html", user: user)
    else
      redirect(conn, to: user_path(conn, :edit))
    end 
  end

  def edit(conn, _params) do
    if logged_in?(conn) do
      user = Repo.get!(User, current_user(conn).id)
      changeset = User.changeset(user)
      render(conn, "edit.html", user: user, changeset: changeset)
    else
      conn
      |> put_flash(:info, "ユーザー限定機能を行うにはログインが必要です")
      |> redirect(to: session_path(conn, :new))  
    end
  end


#↓本当はwith文を使いたい


  def upload_photo(conn, %{"upload" => %{"file" => file}}) do
    user = Repo.get!(User, current_user(conn).id)
    changeset = User.changeset(user)
    bucket =  @default_bucket <> current_user(conn).username
    case File.read(file.path) do
      {:ok, file_binary} ->
        case S3.put_object(bucket, "profile", file_binary)
             |> ExAws.request() do
          {:ok, _} -> 
            case S3.presigned_url(ExAws.Config.new(:s3), :get, bucket, "profile", [virtual_host: true]) do
              {:ok, url} ->
                user
                |> User.changeset(%{userimageurl: url})
                |> Repo.update()
                conn
                |> put_flash(:success, "File uploaded successfully!")
                |> render(conn, "edit.html", user: user, changeset: changeset)
              _ ->
                conn
                |> put_flash(:success, "File uploaded failed!")
                |> render(conn, "edit.html", user: user, changeset: changeset)
            end
          _ ->
            conn
            |> put_flash(:success, "File uploaded failed!")
            |> render(conn, "edit.html", user: user, changeset: changeset)
        end
      _ ->
        conn
        |> put_flash(:success, "File uploaded failed!")
        |> render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def update(conn, %{"username" => username, "user" => user_params}) do
    user = Repo.get_by(User, username: username)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, _params) do
    if logged_in?(conn) do
      username = current_user(conn).username
      Social
      |> where([s], s.follow == ^username)
      |> Repo.delete_all()
      Social
      |> where([s], s.followed == ^username)
      |> Repo.delete_all()
      Posts
      |> where([p], p.username == ^username)
      |> Repo.delete_all()
      user = Repo.get!(User, current_user(conn).id)
      # Here we use delete! (with a bang) because we expect
      # it to always work (and if it does not, it will raise).
      Repo.delete!(user)

      force_delete_bucket(username)

      conn
      |> put_flash(:info, "User deleted successfully.")
      |> redirect(to: user_path(conn, :index))
    else
      conn
      |> put_flash(:info, "ユーザー限定機能を行うにはログインが必要です")
      |> redirect(to: session_path(conn, :new))  
    end
  end

  def force_delete_bucket(username) do
    bucket = @default_bucket <> username
    %{body: %{contents: contents}} =
      bucket
      |> ExAws.S3.list_objects()
      |> ExAws.request!()

    objects =
      contents
      |> Enum.map(& &1.key)

    ExAws.S3.delete_all_objects(bucket, objects)
    |> ExAws.request!()

    ExAws.S3.delete_bucket(bucket)
    |> ExAws.request()
    end
end

web/views/user_view.ex
defmodule PhxBlog.UserView do
  use PhxBlog.Web, :view
end

web/templates/user/edit.html.eex
<h2>Myprofile</h2>


  <div class =" card m-3">
    <img src=
      <%= if @user.userimageurl do %>
        <%= @user.userimageurl %>          
      <% else %>
        "http://via.placeholder.com/320x320"
      <% end %>
     width = "320" height = "320" alt = "profile" class = "card-image-top mx-auto" >
  </div>
  <%= form_for @conn, user_path(@conn, :upload_photo), [as: "upload", multipart: :true], fn f -> %>  
    <%= file_input f, :file, accept: "image/*" %>
    <button class="btn btn-primary" type="submit">Upload</button>
  <% end %>


  <%= render "edit_form.html", changeset: @changeset, user: @user,
                        action: user_path(@conn, :update) %>
  <%= link "New posts", to: posts_path(@conn, :new), class: "btn btn-default btn-xs" %>
<div id="wrap">
  <div id="left">
    <h3>Follow</h3>
    <ul>
      <%= for follows <- follow(@conn) do %>
        <li>
          <%= link follows.followed, to: user_path(@conn, :show, follows.followed) %>
          <%= link "Unfollow", to: social_path(@conn, :delete, follows.followed), method: :delete, class: "btn btn-danger btn-xs" %>
          </li>
      <% end %>
    </ul>
  </div>
  <div id="right">
    <h3>Follower</h3>
    <ul>
      <%= for followers <- follower(@conn) do %>
        <li>
          <%= link followers.follow, to: user_path(@conn, :show, followers.follow) %>
          <%= if follow?(@conn, @user.username) do %>
            <%= link "Unfollow", to: social_path(@conn, :delete, @user.username), method: :delete, class: "btn btn-danger btn-xs" %>
          <% else %>
            <%= render PhxBlog.SocialView, "form.html", conn: @conn, username: @user.username, action: social_path(@conn, :create) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%= link "Delete", to: user_path(@conn, :delete), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>

web/templates/user/edit_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
 <%= hidden_input f, :username, value: @user.username, class: "form-control" %>
  <%= hidden_input f, :password, value: @user.crypted_password, class: "form-control" %>

<ul>

 <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.crypted_password %>
  </li>

  <li>
    <strong>Nickname:</strong>
      <%= text_input f, :nickname, value: @user.nickname, class: "form-control" %>
      <%= error_tag f, :nickname %>
  </li>

</ul>
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Nickname</th>
      <th>Userimageurl</th>
      <%= if logged_in?(@conn) do %>
        <th>Follow</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= link user.username , to: user_path(@conn, :show, user.username) %></td>
      <td><%= user.nickname %></td>
      <td><%= user.userimageurl %></td>
      <%= if logged_in?(@conn) do %>
        <td>
          <%= if follow?(@conn, user.username) do %>
            <%= link "Unfollow", to: social_path(@conn, :delete, user.username), method: :delete, class: "btn btn-danger btn-xs" %>
          <% else %>
            <%= render PhxBlog.SocialView, "form.html", conn: @conn, username: user.username, action: social_path(@conn, :create) %>
          <% end %>

            </td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/user/new.html.eex
<h2>ユーザー登録</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <div class =" card m-3">
      <img src=
        <%= if @user.userimageurl do %>
          <%= @user.userimageurl %>          
        <% else %>
          "http://via.placeholder.com/320x320"
        <% end %>
       width = "320" height = "320" alt = "profile" class = "card-image-top mx-auto" >
    </div>
  </li>
  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.crypted_password %>
  </li>

  <li>
    <strong>Nickname:</strong>
    <%= @user.nickname %>
  </li>
  <%= if logged_in?(@conn) do %>
    <li>
      <%= if follow?(@conn, @user.username) do %>
        <%= link "Unfollow", to: social_path(@conn, :delete, @user.username), method: :delete, class: "btn btn-danger btn-xs" %>
      <% else %>
        <%= render PhxBlog.SocialView, "form.html", conn: @conn, username: @user.username, action: social_path(@conn, :create) %>
      <% end %>
    </li>
  <% end %>

</ul>

<%= link "Back", to: user_path(@conn, :index) %>