lib/phx_blog_web/router.ex
defmodule PhxBlogWeb.Router do
  use PhxBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhxBlogWeb do
  #   pipe_through :api
  # end
end

web/router.ex
defmodule PhxBlog.Router do
  use PhxBlog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlog do
    pipe_through :browser # Use the default browser stack

    get     "/",                    PostsController, :index

    get     "/users",          UserController, :index
    post    "/users",                   SocialController, :create

    get     "/users/new",      UserController, :new
    post    "/users/new",      UserController, :create

    get     "/users/me",       UserController, :edit
    put     "/users/me",       UserController, :update
    post    "/users/me",       UserController, :upload_photo
    delete  "/users/me",       UserController, :delete
    get     "/users/me/post",       PostsController, :mypost

    get     "/users/:name",    UserController, :show
    get     "/users/:name/post",    PostsController, :userpost
    post    "/users/:name/social",      SocialController, :create
    delete  "/users/:name/social",      SocialController, :delete

    get     "/post",                PostsController, :new
    post    "/post",                PostsController, :create
    get     "/post/:id/edit",       PostsController, :edit
    get     "/post/:id",            PostsController, :show
    patch   "/post/:id",            PostsController, :update
    put     "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete

    post    "/post/:id/comment",            CommentController, :create
    delete  "/post/:id/comment",            CommentController, :delete

    get     "/post/search/:query",  PostsController, :search

    get     "/login",  SessionController, :new
    post    "/login",  SessionController, :create
    delete  "/logout", SessionController, :delete
  end

#  Other scopes may use custom stacks.
  scope "/api/v1", PhxBlog do
    pipe_through :api

    get     "/users/new",      UserController, :new
    post    "/login",  SessionController, :create
    get     "/post",                PostsController, :index
    get     "/users/:id/post",      PostsController, :userpost
    post    "/post",                PostsController, :create
    patch   "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete
    get     "/post/:id",            PostsController, :show
    post    "/post/:id/comment",    CommentController, :create
    get     "/post/search/:query",  PostsController, :search

    resources "/auth", AuthController, except: [:new, :edit]

   end
end

lib/phx_blog_web/views/layout_view.ex
defmodule PhxBlogWeb.LayoutView do
  use PhxBlogWeb, :view
end

web/views/layout_view.ex
defmodule PhxBlog.LayoutView do
  use PhxBlog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PhxBlog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <ul class="nav nav-pills pull-right">
          <%= if logged_in?(@conn) do %>
            <li><%= current_user(@conn).username %></li>
            <li><%= link "ログアウト", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li><%= link "ユーザ登録", to: user_path(@conn, :new) %></li>
            <li><%= link "ログイン", to: session_path(@conn, :new) %></li>
          <% end %>
        </ul>
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><input type="text" id="searchbox" value="">
                <input type="button" value="Search!" onclick="location.href = '/post/search/' + document.getElementById('searchbox').value";></li>
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div id="wrap">
        <main id="main" role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
        <aside id="complementary" role="complementary">
          <div>
            <h2>Links</h2>
            <ul>
              <li><%= link "Top page", to: posts_path(@conn, :index) %></li>
              <li><%= link "User list", to: user_path(@conn, :index) %></li>
              <%= if logged_in?(@conn) do %>
                <li><%= link "My profile", to: user_path(@conn, :edit) %></li>
                <li><%= link "New post", to: posts_path(@conn, :new) %></li>
                <li><%= link "My posts", to: posts_path(@conn, :mypost) %></li>
              <% end %>
            </ul>
          </div>
          <%= render PhxBlog.SidebarView, "ranking.html", conn: @conn %>
        </aside>
      </div>
<br/><br/><br/>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>