lib/phx_blog_web/router.ex
defmodule PhxBlogWeb.Router do
  use PhxBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhxBlogWeb do
  #   pipe_through :api
  # end
end

web/router.ex
defmodule PhxBlog.Router do
  use PhxBlog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxBlog do
    pipe_through :browser # Use the default browser stack

    get     "/",                    PostsController, :index

    get     "/users",          UserController, :index
    post    "/users",                   SocialController, :create

    get     "/users/new",      UserController, :new
    post    "/users/new",      UserController, :create

    get     "/users/me",       UserController, :edit
    put     "/users/me",       UserController, :update
    post    "/users/me",       UserController, :upload_photo
    delete  "/users/me",       UserController, :delete
    get     "/users/me/post",       PostsController, :mypost

    get     "/users/:name",    UserController, :show
    get     "/users/:name/post",    PostsController, :userpost
    post    "/users/:name/social",      SocialController, :create
    delete  "/users/:name/social",      SocialController, :delete

    get     "/post",                PostsController, :new
    post    "/post",                PostsController, :create
    get     "/post/:id/edit",       PostsController, :edit
    get     "/post/:id",            PostsController, :show
    patch   "/post/:id",            PostsController, :update
    put     "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete

    post    "/post/:id/comment",            CommentController, :create
    delete  "/post/:id/comment",            CommentController, :delete

    get     "/post/search/:query",  PostsController, :search

    get     "/login",  SessionController, :new
    post    "/login",  SessionController, :create
    delete  "/logout", SessionController, :delete
  end

#  Other scopes may use custom stacks.
  scope "/api/v1", PhxBlog do
    pipe_through :api

    get     "/users/new",      UserController, :new
    post    "/login",  SessionController, :create
    get     "/post",                PostsController, :index
    get     "/users/:id/post",      PostsController, :userpost
    post    "/post",                PostsController, :create
    patch   "/post/:id",            PostsController, :update
    delete  "/post/:id",            PostsController, :delete
    get     "/post/:id",            PostsController, :show
    post    "/post/:id/comment",    CommentController, :create
    get     "/post/search/:query",  PostsController, :search

    resources "/auth", AuthController, except: [:new, :edit]

   end
end

web/models/comment.ex
defmodule PhxBlog.Comment do
  use PhxBlog.Web, :model

  schema "comment" do
    field :title, :string
    field :name, :string
    field :body, :string
    field :pass, :string
    field :mail, :string
    field :post_id, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :name, :body, :pass, :mail, :post_id])
    |> validate_required([:title, :body, :post_id])
  end
end

web/controllers/comment_controller.ex
defmodule PhxBlog.CommentController do
  use PhxBlog.Web, :controller

  alias PhxBlog.Comment

  def comment_index(conn, %{"id" => id}) do
    comment = Comment
              |> where([c], c.post_id == ^id)
              |> Repo.all()
    comment
  end

  def create(conn, %{"comment" => comment_params, "id" => id}) do
    changeset = Comment.changeset(%Comment{}, comment_params)

    case Repo.insert(changeset) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: posts_path(conn, :show, id))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = Repo.get!(Comment, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: posts_path(conn, :show, id))
  end
end

web/views/comment_view.ex
defmodule PhxBlog.CommentView do
  use PhxBlog.Web, :view
end

web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :pass, class: "control-label" %>
    <%= text_input f, :pass, class: "form-control" %>
    <%= error_tag f, :pass %>
  </div>

  <div class="form-group">
    <%= label f, :mail, class: "control-label" %>
    <%= text_input f, :mail, class: "form-control" %>
    <%= error_tag f, :mail %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/comment/index.html.eex
<h2>Comments</h2>
<table class="table">
  <thead>
  </thead>
  <tbody>
    <ol>
<%= for comment <- comment_index(@conn, @id) do %>
      <li>
        <tr>
          <td>Title</td>
          <td><%= comment.title %></td>
        </tr>
        <tr>
          <td>Body</td>
          <td><%= comment.body %></td>
        </tr>
        <tr>
          <td>Name</td>
          <td><%= link comment.name, to: comment.mail %></td>
        </tr>
      </li>
<% end %>
    </ol>
  </tbody>
</table>

web/templates/comment/new.html.eex
<h2>New comment</h2>

<%= render PhxBlog.CommentView, "form.html", changeset: @changeset, action: comment_path(@conn, :create, @id) %>